### ISSUE TITLE
UX - kebab icon should never open a dialog

### ISSUE THREAD

**Issue by himdel** [PSilling/rh-massages#147]
![kebab](https://user-images.githubusercontent.com/289743/74736660-22e9e480-524b-11ea-899b-33e9b3c87bf7.png)

Clicking on the kebab icon usually leads to a dropdown menu with options.
It **never** leads to a modal dialog in other apps.

We should use a different icon for a popup modal with details.

**Comment by PSilling** [comment]
Could you give me some ideas for a Font Awesome replacement? Would horizontal ellipsis work better?

Other than that I do not see any other good option. There are icons like bars, file, address card or clipboard list but while these could technically work, they do not solve this issue at all.

**Comment by himdel** [comment]
Well, glyphicons has a `modal-window` icon, but maybe it's better to stay with font awesome, so...

what about `fa-edit` or `fa-pencil-alt`?

![fa](https://user-images.githubusercontent.com/289743/74834274-05804d80-5313-11ea-99f7-252409c0cbf0.png)

**Comment by PSilling** [comment]
I think it would be acceptable to mix Font Awesome icons with Glyphicons in this case, but I feel that `glyphicon-modal-window` is not self-explanatory. I would like to avoid that.

On the other hand, I think that `fa-edit` could be used. The only problem is that I already use it for administrators for massage editation. But I believe I could replace that with `fa-pencil-alt`. From UX perspective it may be a little confusing but most users will not even see it at all (plus it is planned to add simple titles to all these buttons).

EDIT: Or maybe to avoid confusion due to the usage of two edit buttons, how about we simply use `fa-info`?
![fa-info](https://user-images.githubusercontent.com/25779637/74839202-2c477f80-5325-11ea-9608-80235e45cac7.png)

**Comment by himdel** [comment]
I think any of those could work :) Though fa-info *may* be confused with a help button, not sure.

I've also found `pficon-arrow` ( https://www.patternfly.org/v3/styles/icons/index.html ) which may be a better "opening something" indicator, but may be confusing if people expect it to open something in a new tab.

Choices are hard :)

**Comment by PSilling** [comment]
Yes, they certainly are :+1:

Anyway, I also think that `pficon-arrow` may be quite confusing, so I will probably stick with the edit icons. Thanks!
